# const { email, login, name, password,birthDate,country } = req.body
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "email":"anton@gmail.com",
    "login":"antonLogin",
    "name":"Anton",
    "password":"anton",
    "birthDate":"10.01.2005",
    "country":"USA"
}
###

# const { email / login, password } = req.body
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "emailOrLogin":"anton@gmail.com",
    "password":"anton"
}

###
GET http://localhost:5000/api/users
###

GET http://localhost:5000/api/user/antonLogin
###

POST http://localhost:5000/api/logout
Content-Type: application/json

{
    "userId":"33"
}
###

GET http://localhost:5000/api/countries